FROM golang:1.24.3

RUN useradd -m lune && mkdir -p /home/lune/app/assets/images /home/lune/app/assets/styles

COPY --chown=lune:lune ./* /home/lune/app
COPY --chown=lune:lune ./assets/images/* /home/lune/app/assets/images
COPY --chown=lune:lune ./assets/styles/style.css /home/lune/app/assets/styles

WORKDIR /home/lune/app

RUN go build -o http .

EXPOSE 8080

CMD [ "./http" ]

USER lune
